trigger:
  - next

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseNode@1
    inputs:
      version: '12.x'
  - script: yarn
    displayName: 'Install dependencies'
  - script: node_modules/.bin/electron-rebuild
    displayName: 'Rebuild dependencies for electron'
  - script: yarn lint
    displayName: 'Run linting'
  - script: yarn typings
    displayName: 'Run type checks'
  - script: yarn test
    displayName: 'Run unit tests'
  - script: yarn coverage -t $(CODECOV_TOKEN)
    displayName: 'Publish code coverage report'
  - script: yarn build
    displayName: 'Build package'
