trigger:
  - next

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseNode@1
    inputs:
      version: '12.x'
  - script: yarn install --frozen-lockfile
    displayName: 'Install dependencies'
  - script: yarn lint
    displayName: 'Run linting'
  - script: yarn typings
    displayName: 'Run type checks'
  - script: yarn test
    displayName: 'Run unit tests'
  - script: bash <(curl -s https://codecov.io/bash)
    displayName: 'Publish code coverage report'
  - script: yarn build
    displayName: 'Build package'
